spring.application.name=spring_lec
server.port=80
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true
#db
spring.datasource.url=jdbc:oracle:thin:@10.1.82.127:1521:XE
spring.datasource.username=c##sw1004
spring.datasource.password=sw1004
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver